# Generated by Django 3.0.8 on 2020-08-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='postcode',
        ),
    ]
